set(ATLAS_FOUND 1 CACHE INTERNAL "ATLAS_FOUND")
set(ATLAS_ROOT ${3RD_ROOT}/atlas CACHE INTERNAL "ATLAS_ROOT")
set(ATLAS_INCLUDE_DIRS ${ATLAS_ROOT}/include CACHE INTERNAL "ATLAS_INCLUDE_DIRS")
set(ATLAS_LIBRARY_DIRS ${ATLAS_ROOT}/lib CACHE INTERNAL "ATLAS_LIBRARY_DIRS")
file(GLOB LIBRARIES "${ATLAS_LIBRARY_DIRS}/*.so")
set(ATLAS_LIBRARIES ${LIBRARIES} CACHE INTERNAL "ATLAS_LIBRARIES")

include_directories(${ATLAS_INCLUDE_DIRS})
link_directories(${ATLAS_LIBRARY_DIRS})