set(CALIBRATION_FOUND 1 CACHE INTERNAL "CALIBRATION_FOUND")
set(CALIBRATION_ROOT ${3RD_ROOT}/calibration-release CACHE INTERNAL "CALIBRATION_ROOT")
set(CALIBRATION_INCLUDE_DIRS ${CALIBRATION_ROOT}/include CACHE INTERNAL "CALIBRATION_INCLUDE_DIRS")
set(CALIBRATION_LIBRARY_DIRS ${CALIBRATION_ROOT}/lib CACHE INTERNAL "CALIBRATION_LIBRARY_DIRS")
file(GLOB LIBRARIES "${CALIBRATION_LIBRARY_DIRS}/lib*")
set(CALIBRATION_LIBRARIES ${LIBRARIES} CACHE INTERNAL "CALIBRATION_LIBRARIES")

include_directories(${CALIBRATION_INCLUDE_DIRS})
link_directories(${CALIBRATION_LIBRARY_DIRS})
