set(CERES_FOUND 1 CACHE INTERNAL "CERES_FOUND")
set(CERES_ROOT ${3RD_ROOT}/ceres-solver CACHE INTERNAL "CERES_ROOT")
set(CERES_INCLUDE_DIRS ${CERES_ROOT}/include CACHE INTERNAL "CERES_INCLUDE_DIRS")
set(CERES_LIBRARY_DIRS ${CERES_ROOT}/lib CACHE INTERNAL "CERES_LIBRARY_DIRS")
file(GLOB LIBRARIES "${CERES_LIBRARY_DIRS}/*.so")
set(CERES_LIBRARIES ${LIBRARIES} CACHE INTERNAL "CERES_LIBRARIES")

include_directories(${CERES_INCLUDE_DIRS})
link_directories(${CERES_LIBRARY_DIRS})